### ISSUE TITLE
Any examples with SQL?

### ISSUE THREAD

**Issue by CalebKing3** [khandelwal-arpit/springboot-starterkit#2]
Sorry for opening an issue. Didn't know how else to get in contact.

I think this is a great template. 

Curious if you have any examples using MySQL as the DB. I would like to use pieces of this template but leveraging something like Spring Data as well.

Also available on twitter if that is easier to communicate. @KingCaleb3

**Comment by khandelwal-arpit** [comment]
Hi Caleb,

Thanks for sharing your thoughts. 

Unfortunately I didn't prepare the MySQL version of this particular example. Though, I do have some other contributions with PostgreSQL and H2 database with SpringBoot that you can refer. Here are the links for them - 

https://github.com/SystangoTechnologies/Springboard
https://github.com/SystangoTechnologies/BankOfSpring

Keep reading!
