### ISSUE TITLE
Arpit, is there a User ie mobile build somewhere you mentioned its coming ?

### ISSUE THREAD

**Issue by johnda98** [khandelwal-arpit/springboot-starterkit#5]
RE: End user can use their mobile application

The End user can use their mobile application (yet to be built, however the REST APIs are ready and could be used via Postman or Swagger) to perform the following actions :

**Comment by khandelwal-arpit** [comment]
Hi John,

Unfortunately I never really got a chance to create a mobile application for this starter kit. However the rest apis are there and they could be used in any native/hybrid mobile app, it's just I haven't created one yet.

**Comment by johnda98** [comment]
Arpit.. trying to contact you 
RE your BRS Springboot proj.. any kind suggestions how .. which css file.. bootstrap presumably.. to change the font size etc, globally ? for that theme.     does the bootstrap require separate compile ? / build to pull in a css change ?  I changed a few rems but not effect upon a spring re-build run. please advise. m thanks
